### ISSUE TITLE
Inference results are not saved.

### ISSUE THREAD

**Issue by JunMa11** [shirgur/UMIS#6]
Dear @shirgur 

It seems the inference results are not saved into local hard drives in `train_unsup.py`.

https://github.com/shirgur/UMIS/blob/1baf4b116c3c8b4b8288822c7f72089bec014ebe/train_unsup.py#L226-L235

Best,
Jun

**Comment by shirgur** [comment]
They are logged by Tensorboard.

You can start one and set ```--logdir=run```
